export const categoryProductsActionTypes = {
    GET_CATEGORY_PRODUCTS_START: "GET_CATEGORY_PRODUCTS_START",
    GET_CATEGORY_PRODUCTS_SUCCESS: "GET_CATEGORY_PRODUCTS_SUCCESS",
    GET_CATEGORY_PRODUCTS_FAILURE: "GET_CATEGORY_PRODUCTS_FAILURE",
}